### ISSUE TITLE
Problem with & in LIKE query.

### ISSUE THREAD

**Issue by jgasperlin** [TFaga/lynx#2]
If i include & or %26 in query like this:

"where=title:like:'Tools & Furniture'&limit=30"

It returns wrong result.

Problem is in code:

QueryStringBuilder 182:
for (String pair : query.split("&")) {

I changed regex from "&" to "&(?=([^']*'[^']*')*[^']*$)", to ignore '&' between two '.

**Comment by TFaga** [comment]
Hey, 

Thanks for the info. Will add your fix ASAP.
